services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    volumes:
      - mongo-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongoadmin
      - MONGO_INITDB_ROOT_PASSWORD=secret
    ports:
      - "27018:27017"
    networks:
      - fullstack-chatapp

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: full-stack_backend
    restart: always
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongoadmin:secret@mongodb:27017/dbname?authSource=admin
      - JWT_SECRET=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9...
      - PORT=5001
    depends_on:
      - mongodb
    ports:
      - "5001:5001"
    networks:
      - fullstack-chatapp

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: full-stack_frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - fullstack-chatapp

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    restart: always
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - fullstack-chatapp

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: always
    ports:
      - "3000:3000"  # Grafana UI available at http://localhost:3000
    volumes:
      - grafana-data:/var/lib/grafana
    depends_on:
      - prometheus
    networks:
      - fullstack-chatapp

networks:
  fullstack-chatapp:
    driver: bridge

volumes:
  mongo-data:
  grafana-data:

