global:
  scrape_interval: 1m # Adjust the scrape interval

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"] # Scrapes Prometheus itself

  - job_name: "backend"
    static_configs:
      - targets: ["full-stack_backend:5001"] # Scrapes backend metrics
